Create blockchain better than Bitcoin: private, unlimited blocksize, millisecond confirmations

diff --git a/packaging/rpm-oel/mysql.init b/packaging/rpm-oel/mysql.init
--- a/packaging/rpm-oel/mysql.init
+++ b/packaging/rpm-oel/mysql.init
@@ -1,13 +1,13 @@
 #!/bin/sh
 #
-# mysqld	This shell script takes care of starting and stopping
-#		the MySQL subsystem (mysqld).
+# myblockchaind	This shell script takes care of starting and stopping
+#		the MyBlockchain subsystem (myblockchaind).
 #
 # chkconfig: - 64 36
-# description:	MySQL database server.
-# processname: mysqld
+# description:	MyBlockchain blockchain server.
+# processname: myblockchaind
 # config: /etc/my.cnf
-# pidfile: /var/run/mysqld/mysqld.pid
+# pidfile: /var/run/myblockchaind/myblockchaind.pid
 
 # Source function library.
 . /etc/rc.d/init.d/functions
@@ -16,10 +16,10 @@
 . /etc/sysconfig/network
 
 
-exec="/usr/bin/mysqld_safe"
-prog="mysqld"
+exec="/usr/bin/myblockchaind_safe"
+prog="myblockchaind"
 
-# Set timeouts here so they can be overridden from /etc/sysconfig/mysqld
+# Set timeouts here so they can be overridden from /etc/sysconfig/myblockchaind
 STARTTIMEOUT=120
 STOPTIMEOUT=600
 
@@ -27,16 +27,16 @@ STOPTIMEOUT=600
 
 lockfile=/var/lock/subsys/$prog
 
-# Support for extra options passed to mysqld
+# Support for extra options passed to myblockchaind
 command=$1 && shift
 extra_opts="$@"
 
-# extract value of a MySQL option from config files
-# Usage: get_mysql_option SECTION VARNAME DEFAULT
+# extract value of a MyBlockchain option from config files
+# Usage: get_myblockchain_option SECTION VARNAME DEFAULT
 # result is returned in $result
 # We use my_print_defaults which prints all options from multiple files,
 # with the more specific ones later; hence take the last match.
-get_mysql_option(){
+get_myblockchain_option(){
 	result=`/usr/bin/my_print_defaults "$1" | sed -n "s/^--$2=//p" | tail -n 1`
 	if [ -z "$result" ]; then
 	    # not found, use default
@@ -44,13 +44,13 @@ get_mysql_option(){
 	fi
 }
 
-get_mysql_option mysqld datadir "/var/lib/mysql"
+get_myblockchain_option myblockchaind datadir "/var/lib/myblockchain"
 datadir="$result"
-get_mysql_option mysqld socket "$datadir/mysql.sock"
+get_myblockchain_option myblockchaind socket "$datadir/myblockchain.sock"
 socketfile="$result"
-get_mysql_option mysqld_safe log-error "/var/log/mysqld.log"
+get_myblockchain_option myblockchaind_safe log-error "/var/log/myblockchaind.log"
 errlogfile="$result"
-get_mysql_option mysqld_safe pid-file "/var/run/mysqld/mysqld.pid"
+get_myblockchain_option myblockchaind_safe pid-file "/var/run/myblockchaind/myblockchaind.pid"
 mypidfile="$result"
 
 case $socketfile in
@@ -61,21 +61,21 @@ esac
 install_validate_password_sql_file () {
     local dir
     local initfile
-    if [ -d /var/lib/mysql-files ]; then
-        dir=/var/lib/mysql-files
+    if [ -d /var/lib/myblockchain-files ]; then
+        dir=/var/lib/myblockchain-files
     else
         dir=/tmp
     fi
     initfile="$(mktemp $dir/install-validate-password-plugin.XXXXXX.sql)"
-    chown mysql:mysql "$initfile"
-    echo "INSERT INTO mysql.plugin (name, dl) VALUES ('validate_password', 'validate_password.so');" > $initfile
+    chown myblockchain:myblockchain "$initfile"
+    echo "INSERT INTO myblockchain.plugin (name, dl) VALUES ('validate_password', 'validate_password.so');" > $initfile
     echo $initfile
 }
 
 start(){
     [ -x $exec ] || exit 5
     # check to see if it's already running
-    RESPONSE=$(/usr/bin/mysqladmin --no-defaults --socket="$adminsocket" --user=UNKNOWN_MYSQL_USER ping 2>&1)
+    RESPONSE=$(/usr/bin/myblockchainadmin --no-defaults --socket="$adminsocket" --user=UNKNOWN_MYBLOCKCHAIN_USER ping 2>&1)
     if [ $? = 0 ]; then
 	# already running, do nothing
 	action $"Starting $prog: " /bin/true
@@ -88,36 +88,36 @@ start(){
     else
     	# prepare for start
 	touch "$errlogfile"
-	chown mysql:mysql "$errlogfile" 
+	chown myblockchain:myblockchain "$errlogfile" 
 	chmod 0640 "$errlogfile"
 	[ -x /sbin/restorecon ] && /sbin/restorecon "$errlogfile"
-	if [ ! -d "$datadir/mysql" ] ; then
+	if [ ! -d "$datadir/myblockchain" ] ; then
 	    # First, make sure $datadir is there with correct permissions
 	    if [ ! -e "$datadir" -a ! -h "$datadir" ]
 	    then
 		mkdir -p "$datadir" || exit 1
 	    fi
-	    chown mysql:mysql "$datadir"
+	    chown myblockchain:myblockchain "$datadir"
 	    chmod 0755 "$datadir"
 	    [ -x /sbin/restorecon ] && /sbin/restorecon "$datadir"
-	    # Now create the database
+	    # Now create the blockchain
             initfile="$(install_validate_password_sql_file)"
-	    action $"Initializing MySQL database: " /usr/sbin/mysqld --initialize --datadir="$datadir" --user=mysql --init-file="$initfile"
+	    action $"Initializing MyBlockchain blockchain: " /usr/sbin/myblockchaind --initialize --datadir="$datadir" --user=myblockchain --init-file="$initfile"
 	    ret=$?
             rm -f "$initfile"
-	    chown -R mysql:mysql "$datadir"
+	    chown -R myblockchain:myblockchain "$datadir"
             # Generate certs if needed
-            if [ -x /usr/bin/mysql_ssl_rsa_setup -a ! -e "${datadir}/server-key.pem" ] ; then
-                /usr/bin/mysql_ssl_rsa_setup --datadir="$datadir" --uid=mysql >/dev/null 2>&1
+            if [ -x /usr/bin/myblockchain_ssl_rsa_setup -a ! -e "${datadir}/server-key.pem" ] ; then
+                /usr/bin/myblockchain_ssl_rsa_setup --datadir="$datadir" --uid=myblockchain >/dev/null 2>&1
             fi
 	    if [ $ret -ne 0 ] ; then
 		return $ret
 	    fi
 	fi
-	chown mysql:mysql "$datadir"
+	chown myblockchain:myblockchain "$datadir"
 	chmod 0755 "$datadir"
 	# Pass all the options determined above, to ensure consistent behavior.
-	# In many cases mysqld_safe would arrive at the same conclusions anyway
+	# In many cases myblockchaind_safe would arrive at the same conclusions anyway
 	# but we need to be sure.  (An exception is that we don't force the
 	# log-error setting, since this script doesn't really depend on that,
 	# and some users might prefer to configure logging to syslog.)
@@ -125,19 +125,19 @@ start(){
 	# alarms, per bug #547485
 	$exec   --datadir="$datadir" --socket="$socketfile" \
 		--pid-file="$mypidfile" \
-		--basedir=/usr --user=mysql $extra_opts >/dev/null 2>&1 &
+		--basedir=/usr --user=myblockchain $extra_opts >/dev/null 2>&1 &
 	safe_pid=$!
 	# Spin for a maximum of N seconds waiting for the server to come up;
-	# exit the loop immediately if mysqld_safe process disappears.
+	# exit the loop immediately if myblockchaind_safe process disappears.
 	# Rather than assuming we know a valid username, accept an "access
 	# denied" response as meaning the server is functioning.
 	ret=0
 	TIMEOUT="$STARTTIMEOUT"
 	while [ $TIMEOUT -gt 0 ]; do
-	    RESPONSE=$(/usr/bin/mysqladmin --no-defaults --socket="$adminsocket" --user=UNKNOWN_MYSQL_USER ping 2>&1) && break
+	    RESPONSE=$(/usr/bin/myblockchainadmin --no-defaults --socket="$adminsocket" --user=UNKNOWN_MYBLOCKCHAIN_USER ping 2>&1) && break
 	    echo "$RESPONSE" | grep -q "Access denied for user" && break
 	    if ! /bin/kill -0 $safe_pid 2>/dev/null; then
-		echo "MySQL Daemon failed to start."
+		echo "MyBlockchain Daemon failed to start."
 		ret=1
 		break
 	    fi
@@ -145,7 +145,7 @@ start(){
 	    let TIMEOUT=${TIMEOUT}-1
 	done
 	if [ $TIMEOUT -eq 0 ]; then
-	    echo "Timeout error occurred trying to start MySQL Daemon."
+	    echo "Timeout error occurred trying to start MyBlockchain Daemon."
 	    ret=1
 	fi
 	if [ $ret -eq 0 ]; then
@@ -164,19 +164,19 @@ stop(){
 	    action $"Stopping $prog: " /bin/true
 	    return 0
 	fi
-	MYSQLPID=`cat "$mypidfile"`
-	if [ -n "$MYSQLPID" ]; then
-	    /bin/kill "$MYSQLPID" >/dev/null 2>&1
+	MYBLOCKCHAINPID=`cat "$mypidfile"`
+	if [ -n "$MYBLOCKCHAINPID" ]; then
+	    /bin/kill "$MYBLOCKCHAINPID" >/dev/null 2>&1
 	    ret=$?
 	    if [ $ret -eq 0 ]; then
 		TIMEOUT="$STOPTIMEOUT"
 		while [ $TIMEOUT -gt 0 ]; do
-		    /bin/kill -0 "$MYSQLPID" >/dev/null 2>&1 || break
+		    /bin/kill -0 "$MYBLOCKCHAINPID" >/dev/null 2>&1 || break
 		    sleep 1
 		    let TIMEOUT=${TIMEOUT}-1
 		done
 		if [ $TIMEOUT -eq 0 ]; then
-		    echo "Timeout error occurred trying to stop MySQL Daemon."
+		    echo "Timeout error occurred trying to stop MyBlockchain Daemon."
 		    ret=1
 		    action $"Stopping $prog: " /bin/false
 		else
diff --git a/packaging/rpm-sles/mysql.init b/packaging/rpm-sles/mysql.init
--- a/packaging/rpm-sles/mysql.init
+++ b/packaging/rpm-sles/mysql.init
@@ -16,23 +16,23 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 
 
-# MySQL Database start/stop script
+# MyBlockchain Database start/stop script
 
 # chkconfig:   - 64 36
-# description: MySQL Database
-# processname: mysqld
+# description: MyBlockchain Database
+# processname: myblockchaind
 # config:      /etc/my.cnf
-# pidfile:     /var/run/mysql/mysqld.pid
+# pidfile:     /var/run/myblockchain/myblockchaind.pid
 
 # Comments to support LSB init script conventions
 ### BEGIN INIT INFO
-# Provides:          mysql
+# Provides:          myblockchain
 # Required-Start:    $network $remote_fs
 # Required-Stop:     $network $remote_fs
 # Default-Start:     3 5
 # Default-Stop:      0 1 6
-# Short-Description: MySQL Database
-# Description:       MySQL Database
+# Short-Description: MyBlockchain Database
+# Description:       MyBlockchain Database
 ### END INIT INFO
 
 # 
@@ -45,14 +45,14 @@ rc_reset
 
 STARTTIMEOUT=180
 STOPTIMEOUT=600
-PROG=/usr/bin/mysqld_safe
+PROG=/usr/bin/myblockchaind_safe
 
-[ -e /etc/sysconfig/mysql ] && . /etc/sysconfig/mysql
+[ -e /etc/sysconfig/myblockchain ] && . /etc/sysconfig/myblockchain
 
 # Lock directory
-lockfile=/var/lock/subsys/mysql
+lockfile=/var/lock/subsys/myblockchain
 
-# Support for extra options passed to mysqld
+# Support for extra options passed to myblockchaind
 command=$1 && shift
 extra_opts="$@"
 
@@ -65,54 +65,54 @@ get_option () {
     echo $ret
 }
 
-datadir=$(get_option mysqld datadir "/var/lib/mysql")
-socket=$(get_option  mysqld socket "$datadir/mysql.sock")
-pidfile=$(get_option mysqld_safe pid-file "/var/run/mysql/mysqld.pid")
-logfile=$(get_option mysqld_safe log-error "/var/log/mysql/mysqld.log")
+datadir=$(get_option myblockchaind datadir "/var/lib/myblockchain")
+socket=$(get_option  myblockchaind socket "$datadir/myblockchain.sock")
+pidfile=$(get_option myblockchaind_safe pid-file "/var/run/myblockchain/myblockchaind.pid")
+logfile=$(get_option myblockchaind_safe log-error "/var/log/myblockchain/myblockchaind.log")
 
 install_validate_password_sql_file () {
     local dir
     local initfile
-    if [ -d /var/lib/mysql-files ]; then
-        dir=/var/lib/mysql-files
+    if [ -d /var/lib/myblockchain-files ]; then
+        dir=/var/lib/myblockchain-files
     else
         dir=/tmp
     fi
     initfile="$(mktemp $dir/install-validate-password-plugin.XXXXXX.sql)"
-    chown mysql:mysql "$initfile"
-    echo "INSERT INTO mysql.plugin (name, dl) VALUES ('validate_password', 'validate_password.so');" > $initfile
+    chown myblockchain:myblockchain "$initfile"
+    echo "INSERT INTO myblockchain.plugin (name, dl) VALUES ('validate_password', 'validate_password.so');" > $initfile
     echo $initfile
 }
 
 install_db () {
-    # Note: something different than datadir=/var/lib/mysql requires 
+    # Note: something different than datadir=/var/lib/myblockchain requires 
     # SELinux policy changes (in enforcing mode)
-    datadir=$(get_option mysqld datadir "/var/lib/mysql")
-    logfile=$(get_option mysqld_safe log-error "/var/log/mysql/mysqld.log")
+    datadir=$(get_option myblockchaind datadir "/var/lib/myblockchain")
+    logfile=$(get_option myblockchaind_safe log-error "/var/log/myblockchain/myblockchaind.log")
 
     # Restore log, dir, perms and SELinux contexts
-    [ -d "$datadir" ] || install -d -m 0755 -omysql -gmysql "$datadir" || return 1
+    [ -d "$datadir" ] || install -d -m 0755 -omyblockchain -gmyblockchain "$datadir" || return 1
 
     [ -e $logfile ] || touch $logfile || return 1
     chmod 0640 $logfile
-    chown mysql:mysql $logfile || return 1
+    chown myblockchain:myblockchain $logfile || return 1
     if [ -x /usr/sbin/restorecon ]; then
         /usr/sbin/restorecon "$datadir"
         /usr/sbin/restorecon $logfile
     fi
 
-    # If special mysql dir is in place, skip db install 
-    [ -d "$datadir/mysql" ] && return 0
+    # If special myblockchain dir is in place, skip db install 
+    [ -d "$datadir/myblockchain" ] && return 0
 
     # Create initial db and install validate password plugin
     initfile="$(install_validate_password_sql_file)"
-    /usr/sbin/mysqld --initialize --datadir="$datadir" --user=mysql --init-file="$initfile"
+    /usr/sbin/myblockchaind --initialize --datadir="$datadir" --user=myblockchain --init-file="$initfile"
     ret=$?
     rm -f "$initfile"
 
     # Generate certs if neded
-    if [ -x /usr/bin/mysql_ssl_rsa_setup -a ! -e "${datadir}/server-key.pem" ] ; then
-        /usr/bin/mysql_ssl_rsa_setup --datadir="$datadir" --uid=mysql >/dev/null 2>&1
+    if [ -x /usr/bin/myblockchain_ssl_rsa_setup -a ! -e "${datadir}/server-key.pem" ] ; then
+        /usr/bin/myblockchain_ssl_rsa_setup --datadir="$datadir" --uid=myblockchain >/dev/null 2>&1
     fi
     return $ret
 }
@@ -120,16 +120,16 @@ install_db () {
 # Wait for ping to answer to signal startup completed,
 # might take a while in case of e.g. crash recovery
 pinger () {
-    mysqld_safe_pid=$1
+    myblockchaind_safe_pid=$1
     timer=$STARTTIMEOUT
     ret=0
     while [ $timer -gt 0 ]; do
         sleep 1
-        mysqladmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 && break
+        myblockchainadmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 && break
 	timer=$(expr $timer - 1)
 
-	# Check if mysqld_safe is still alive, if not there is no hope
-	if ! kill -0 $mysqld_safe_pid >/dev/null 2>&1 ; then
+	# Check if myblockchaind_safe is still alive, if not there is no hope
+	if ! kill -0 $myblockchaind_safe_pid >/dev/null 2>&1 ; then
 	    ret=1
 	    break
 	fi
@@ -137,13 +137,13 @@ pinger () {
     
     # Did we timeout?
     if [ $timer = 0 ]; then
-	echo "MySQL Database start up timeout after ${STARTTIMEOUT}s"
+	echo "MyBlockchain Database start up timeout after ${STARTTIMEOUT}s"
 	ret=1
     fi
     return $ret
 }
 
-# Check if mysqld is running
+# Check if myblockchaind is running
 chk_running () {
     ret=0
     if [ -e "$pidfile" ]; then
@@ -152,7 +152,7 @@ chk_running () {
 	ret=7
     fi
 
-    # Check if $pid is a mysqld pid
+    # Check if $pid is a myblockchaind pid
     if [ $ret -eq 0 ]; then
 	[ -L "/proc/$pid/exe" ] || ret=7 
     fi
@@ -162,29 +162,29 @@ chk_running () {
     fi
 
     if [ $ret -eq 0 ]; then
-	[ "x$(basename $exec)" = "xmysqld" ] || ret=7
+	[ "x$(basename $exec)" = "xmyblockchaind" ] || ret=7
     fi
     return $ret
 }
 
 start () {
-    if chk_running && mysqladmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 ; then
-	echo -n "Starting service MySQL:"
+    if chk_running && myblockchainadmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 ; then
+	echo -n "Starting service MyBlockchain:"
 	rc_reset ; rc_status -v ; rc_exit
     fi
 
     if ! install_db; then
-	echo -n "MySQL Database could not initialize data directory:"
+	echo -n "MyBlockchain Database could not initialize data directory:"
 	rc_failed 6 ; rc_status -v ; rc_exit
     fi
 
     $PROG --basedir=/usr --datadir="$datadir" --pid-file="$pidfile" $extra_opts >/dev/null 2>&1 &
     if pinger $! ; then
-	echo -n "Starting service MySQL:"
+	echo -n "Starting service MyBlockchain:"
 	touch $lockfile
 	rc_reset
     else
-	echo -n "Failed to start service MySQL:"
+	echo -n "Failed to start service MyBlockchain:"
 	rc_failed 3
     fi
     rc_status -v
@@ -194,7 +194,7 @@ stop () {
     chk_running
     ret=$?
     if [ $ret -ne 0 ]; then
-	echo -n "Shutting down service MySQL:"
+	echo -n "Shutting down service MyBlockchain:"
 	rc_reset ; rc_status -v ; return 0
     fi
 
@@ -211,17 +211,17 @@ stop () {
             timer=$(expr $timer - 1)
 	done
     else
-	echo -n "Shutting down service MySQL:"
+	echo -n "Shutting down service MyBlockchain:"
 	rc_failed 4 ; rc_status -v ; rc_exit
     fi
     
     if [ $timer -eq 0 ]; then
-	echo -n "Failed to stop service MySQL:"
+	echo -n "Failed to stop service MyBlockchain:"
 	rc_failed 1
     else
 	rm -f $lockfile
 	rm -f "$socketfile"
-	echo -n "Shutting down service MySQL:"
+	echo -n "Shutting down service MyBlockchain:"
 	rc_reset
     fi
     rc_status -v
@@ -234,27 +234,27 @@ restart () {
 
 reload () {
     ret=0
-    if chk_running && mysqladmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 ; then
+    if chk_running && myblockchainadmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 ; then
 	pid=$(cat "$pidfile")
 	kill -HUP $pid >/dev/null 2>&1
-	echo -n "Reloading service MySQL:"
+	echo -n "Reloading service MyBlockchain:"
 	rc_reset
     else
-	echo -n "Reloading of service MySQL failed:"
+	echo -n "Reloading of service MyBlockchain failed:"
         rc_failed 7
     fi
     rc_status -v
 }
 
 condrestart () {
-    if chk_running && mysqladmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 ; then
+    if chk_running && myblockchainadmin --no-defaults --socket="$socket" ping >/dev/null 2>&1 ; then
 	restart
     fi
 }
 
 status () {
-   echo -n "Checking for service MySQL:"
-   checkproc mysqld
+   echo -n "Checking for service MyBlockchain:"
+   checkproc myblockchaind
    rc_status -v
 }  
 
diff --git a/storage/ndb/memcache/sandbox.sh.in b/storage/ndb/memcache/sandbox.sh.in
--- a/storage/ndb/memcache/sandbox.sh.in
+++ b/storage/ndb/memcache/sandbox.sh.in
@@ -9,7 +9,7 @@ bindir=@INSTALL_BINDIR@
 libexecdir=@INSTALL_SBINDIR@
 libdir=@INSTALL_LIBDIR@
 scriptsdir=@INSTALL_SCRIPTDIR@
-sharedir=@INSTALL_MYSQLSHAREDIR@
+sharedir=@INSTALL_MYBLOCKCHAINSHAREDIR@
 memcachedbin=@MEMCACHED_BIN_PATH@
 
 SOURCE_DIR=$sourcedir
@@ -36,8 +36,8 @@ if test -d $BUILD_DIR
   MGM_CLIENT_DIR=$BUILD_DIR/storage/ndb/src/mgmclient
   MGM_SERVER_DIR=$BUILD_DIR/storage/ndb/src/mgmsrv
   NDBD_DIR=$BUILD_DIR/storage/ndb/src/kernel
-  MYSQL_CLIENT_DIR=$BUILD_DIR/client
-  MYSQL_SERVER_DIR=$BUILD_DIR/scripts
+  MYBLOCKCHAIN_CLIENT_DIR=$BUILD_DIR/client
+  MYBLOCKCHAIN_SERVER_DIR=$BUILD_DIR/scripts
   ENGINE_SO_DIR=$BUILD_DIR/storage/ndb/memcache
   METADATA_DIR=$BUILD_DIR/scripts/
   SCRIPTS_DIR=$INSTALL_DIR/$scriptsdir    # See NOTE below
@@ -47,27 +47,27 @@ if test -d $BUILD_DIR
   MGM_CLIENT_DIR=$INSTALL_DIR/$libexecdir
   MGM_SERVER_DIR=$INSTALL_DIR/$libexecdir
   NDBD_DIR=$INSTALL_DIR/$libexecdir
-  MYSQL_CLIENT_DIR=$INSTALL_DIR/$bindir
-  MYSQL_SERVER_DIR=$INSTALL_DIR/$libexecdir
+  MYBLOCKCHAIN_CLIENT_DIR=$INSTALL_DIR/$bindir
+  MYBLOCKCHAIN_SERVER_DIR=$INSTALL_DIR/$libexecdir
   ENGINE_SO_DIR=$INSTALL_DIR/$libdir
   METADATA_DIR=$sharedir/memcache-api
   SCRIPTS_DIR=$INSTALL_DIR/$scriptsdir
 fi
 
 ## NOTE.
-##  mysql_install_db only works from an installed copy.
-##  mtr fixes this by reimplementing mysql_install_db internally.
+##  myblockchain_install_db only works from an installed copy.
+##  mtr fixes this by reimplementing myblockchain_install_db internally.
 ##  Our solution for now is to hope we find a copy in the install_dir
  
 test_paths() {
   test_exec_path $MGM_CLIENT_DIR ndb_mgm
   test_exec_path $MGM_SERVER_DIR ndb_mgmd
-  test_exec_path $MYSQL_CLIENT_DIR mysql
-  test_exec_path $MYSQL_CLIENT_DIR mysqladmin
-  test_exec_path $MYSQL_SERVER_DIR mysqld_safe
+  test_exec_path $MYBLOCKCHAIN_CLIENT_DIR myblockchain
+  test_exec_path $MYBLOCKCHAIN_CLIENT_DIR myblockchainadmin
+  test_exec_path $MYBLOCKCHAIN_SERVER_DIR myblockchaind_safe
   test_exec_path $NDBD_DIR ndbd
   test_exec_path $MEMCACHED_DIR memcached
-  test_exec_path $SCRIPTS_DIR mysql_install_db
+  test_exec_path $SCRIPTS_DIR myblockchain_install_db
   test_read_path $ENGINE_SO_DIR ndb_engine.so
   test_read_path $METADATA_DIR ndb_memcache_metadata.sql
 }
@@ -97,10 +97,10 @@ build_dirs() {
 }
 
 write_my_cnf() {
-  ( echo "[mysqld]"
+  ( echo "[myblockchaind]"
     echo "ndbcluster"
     echo "datadir=$HOME_BASE/sandbox/data"
-    echo "pid-file=$HOME_BASE/sandbox/mysqld.pid"
+    echo "pid-file=$HOME_BASE/sandbox/myblockchaind.pid"
     echo "user=$MYSELF"
     echo "innodb_log_file_size=1M"
     echo
@@ -136,21 +136,21 @@ write_cluster_ini() {
 
 do_install_db() {
   OUTFILE=`mktemp`
-  $SCRIPTS_DIR/mysql_install_db \
+  $SCRIPTS_DIR/myblockchain_install_db \
     --basedir=$INSTALL_DIR --datadir=$HOME_BASE/sandbox/data \
     --skip-name-resolve --user=$MYSELF > $OUTFILE
-  if test ! -d $HOME_BASE/sandbox/data/mysql 
-    then echo "Failed: mysql_install_db did not work:"
+  if test ! -d $HOME_BASE/sandbox/data/myblockchain 
+    then echo "Failed: myblockchain_install_db did not work:"
     cat $OUTFILE
     rm $OUTFILE
     exit    
-    else echo "Created MySQL System Tables"
+    else echo "Created MyBlockchain System Tables"
     rm $OUTFILE
   fi
 }
 
-wait_for_mysql_ready() {
-  while ! $MYSQL_CLIENT_DIR/mysqladmin -s ping 
+wait_for_myblockchain_ready() {
+  while ! $MYBLOCKCHAIN_CLIENT_DIR/myblockchainadmin -s ping 
     do
       sleep 1
       echo waiting
@@ -173,14 +173,14 @@ start_ndbd() {
   sleep 5
 }
 
-start_mysql_server() {
-  $MYSQL_SERVER_DIR/mysqld_safe --defaults-file=$HOME_BASE/sandbox/my.cnf &
+start_myblockchain_server() {
+  $MYBLOCKCHAIN_SERVER_DIR/myblockchaind_safe --defaults-file=$HOME_BASE/sandbox/my.cnf &
   sleep 3
-  wait_for_mysql_ready
+  wait_for_myblockchain_ready
 }
 
-mysqld_is_running() {  
-   test_pid mysqld.pid
+myblockchaind_is_running() {  
+   test_pid myblockchaind.pid
 }
 
 mgm_server_is_running() {  
@@ -205,8 +205,8 @@ test_pid() {
 load_metadata() {
   echo Loading NDB Memcache configuration data
   DDL_SCRIPT=$METADATA_DIR/ndb_memcache_metadata.sql
-  $MYSQL_CLIENT_DIR/mysql --connect-timeout=10 -u root < $DDL_SCRIPT || TRY_AGAIN=1
-  test "$TRY_AGAIN" = "1" && $MYSQL_CLIENT_DIR/mysql --connect-timeout=10 \
+  $MYBLOCKCHAIN_CLIENT_DIR/myblockchain --connect-timeout=10 -u root < $DDL_SCRIPT || TRY_AGAIN=1
+  test "$TRY_AGAIN" = "1" && $MYBLOCKCHAIN_CLIENT_DIR/myblockchain --connect-timeout=10 \
     -u root < $DDL_SCRIPT
 }
 
@@ -221,8 +221,8 @@ stop_memcached() {
   test -n "$SERVERPID" && kill $SERVERPID
 }
 
-stop_mysqld() {
-  $MYSQL_CLIENT_DIR/mysqladmin -u root shutdown
+stop_myblockchaind() {
+  $MYBLOCKCHAIN_CLIENT_DIR/myblockchainadmin -u root shutdown
 }
 
 stop_mgm_server() {
@@ -235,13 +235,13 @@ final_message() {
   echo "Sandbox directory is $HOME_BASE/sandbox"
   echo "Memcached is $MEMCACHED_DIR/memcached"
   echo 
-  echo "Use \"sh sandbox.sh stop\" to stop memcached & MySQL Cluster"
+  echo "Use \"sh sandbox.sh stop\" to stop memcached & MyBlockchain Cluster"
   echo 
 }
 
 usage() {
-  echo "sandbox.sh start [ndb_mgmd | ndbd | mysql | memcached]"
-  echo "           stop  [ndb_mgmd | mysql | memcached]"
+  echo "sandbox.sh start [ndb_mgmd | ndbd | myblockchain | memcached]"
+  echo "           stop  [ndb_mgmd | myblockchain | memcached]"
   echo "           status"
   echo
   exit
@@ -256,9 +256,9 @@ cmd_status() {
     then echo "[ndbd]       running"
     else echo "[ndbd]       stopped"
   fi
-  if mysqld_is_running
-    then echo "[mysqld]     running"
-    else echo "[mysqld]     stopped"
+  if myblockchaind_is_running
+    then echo "[myblockchaind]     running"
+    else echo "[myblockchaind]     stopped"
   fi
   if memcached_is_running
     then echo "[memcached]  running"
@@ -268,20 +268,20 @@ cmd_status() {
 
 cmd_stop() {
   test "$1" = "memcached"  &&   stop_memcached   &&  exit
-  test "$1" = "mysqld"     &&   stop_mysqld      &&  exit
+  test "$1" = "myblockchaind"     &&   stop_myblockchaind      &&  exit
   test "$1" = "ndb_mgmd"   &&   stop_mgm_server  &&  exit
 
   test "$1" = ""  ||   usage
 
   # stop all
-  mysqld_is_running        &&   stop_mysqld
+  myblockchaind_is_running        &&   stop_myblockchaind
   memcached_is_running     &&   stop_memcached
   mgm_server_is_running    &&   stop_mgm_server
 }  
 
 cmd_start() {
   test "$1" = "memcached"  &&  start_memcached    && exit
-  test "$1" = "mysqld"     &&  start_mysql_server && exit
+  test "$1" = "myblockchaind"     &&  start_myblockchain_server && exit
   test "$1" = "ndbd"       &&  start_ndbd         && exit
   test "$1" = "ndb_mgmd"   &&  start_mgm_server   && exit
 
@@ -291,10 +291,10 @@ cmd_start() {
   test -d sandbox                     ||  build_dirs
   test -f sandbox/my.cnf              ||  write_my_cnf
   test -f sandbox/cluster.ini         ||  write_cluster_ini
-  test -d sandbox/data/mysql          ||  do_install_db
+  test -d sandbox/data/myblockchain          ||  do_install_db
   mgm_server_is_running               ||  start_mgm_server
   ndbd_is_running                     ||  start_ndbd 
-  mysqld_is_running                   ||  start_mysql_server  
+  myblockchaind_is_running                   ||  start_myblockchain_server  
   test -d sandbox/data/ndbmemcache    ||  load_metadata  
   memcached_is_running                ||  start_memcached
 
